[project]
name = "first-flet-app"
version = "0.1.0"
requires-python = ">=3.9"

dependencies = [
  "flet==0.28.3",
  "httpx==0.28.1"
]

[tool.flet]
org = "com.mycompany"
product = "first-flet-app"
company = "Flet"
copyright = "Copyright (C) 2025"

[tool.flet.app]
path = "src"
